config/routes.rb
Rails.application.routes.draw do

  get 'signup' => 'users#new'
  get 'profile' => 'users#show'
  resources :users

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions

  root 'recipes#index'
  resources :recipes
  
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :recipe
	belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :users, through: :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :recipes, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorite_recipes, through: :favorites, source: :recipe 
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		@current_user != nil
	end

	helper_method :current_user, :logged_in?
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.all
	end

	def new
		if current_user
			@recipe = Recipe.new
		render :new
		else
			redirect_to login_path
		end
	end

	def create
		recipe = current_user.recipes.new(recipe_params)
		if recipe.save
			redirect_to recipe_path(recipe)
		else
			redirect_to new_recipe_path
		end
	end

	def show
		if current_user
			@recipe = Recipe.find(params[:id])
		else
			redirect_to login_path
		end
	end

	def edit
		if current_user
			@recipe = Recipe.find(params[:id])
		else
			redirect_to login_path
		end
	end

	def update
		recipe = Recipe.find(params[:id])
		recipe.update_attributes(recipe_params)
		redirect_to recipe_path(recipe)
	end

	private
	def recipe_params
		params.require(:recipe).permit(:name, :instructions)	
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if current_user
			redirect_to profile_path
		else
			render :new
		end
	end

	def create
		user = User.find_by_email(user_params[:email])
		if user && user.authenticate(user_params[:password])
			session[:user_id] = user.id 
			redirect_to profile_path
		else
			redirect_to login_path
		end	
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

	private
		def user_params
			params.require(:user).permit(:email, :password)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		if current_user
			redirect_to profile_path
		else
			@user = User.new
		end
	end

	def create
		if current_user
			redirect_to current_user
		else
			user = User.new(user_params)
			if user.save
				session[:user_id] = user.id
				redirect_to profile_path
			else
				redirect_to signup_path
			end
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def show
		render :show
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title>Rassipies</title>
	  	<meta name="viewport" content="width=device-width, initial-scale=1">
	  	<%= csrf_meta_tags %>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.6/journal/bootstrap.css" rel="stylesheet">
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>	  
	</head>

	<body>
		<nav class="navbar navbar-default">
		  	<div class="container-fluid">
		  		<div class="navbar-header">
		  			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		  				<span class="sr-only">Toggle navigation</span>
		    			<span class="icon-bar"></span>
		    			<span class="icon-bar"></span>
		    			<span class="icon-bar"></span>
		    		</button>
		    		<%= link_to "Home", root_path %>
		    	</div>

		    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        			<ul class="nav navbar-nav navbar-right">
        				<% if logged_in? %>
        				<li><%= link_to "Profile", profile_path %></li>
        				<li><%= link_to "Log Out", logout_path %></li>
        				<% else %>
        				<li><%= link_to "Log In", login_path %></li>
        				<li><%= link_to "Sign Up", signup_path %></li>
        				<% end %>
        			</ul>
        		</div>
		    </div>
		</nav>

<%= yield %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	</body>
</html>

app/views/recipes/edit.html.erb
<div class="container">
	<h1>Edit Recipe</h1>
	<%= form_for(@recipe) do |f| %>
		<p><%= f.text_field :name, placeholder: "Name" %></p>	
		<p><%= f.text_field :instructions, placeholder: "instructions" %></p>
		<p><%= f.submit "Update" %></p>
	<% end %>	
</div>

app/views/recipes/index.html.erb
<div class="jumbotron">
</div>

<div class="container">
	<div class="row">
		<% @recipes.each do |recipe| %>
		<div class="col-md-4 col-md-offset-2">
			<h2><%= recipe.name %></h2>
			<p><em>Instructions</em>:
				<%= recipe.instructions %>
			</p> 
			<p>
				<%= link_to "View", recipe_path(recipe) %> -
				<%= link_to "Edit", edit_recipe_path(recipe) %>
			</p>
		</div>
		<% end %>	

	<div class="container">
		<div class="row">
				
					<% @recipes.each do |recipe| %>
					<div class="col-md-4 col-md-offset-2">
						<h2><%= recipe.name %></h2>
						<%= recipe.instructions %> -
						<%= link_to "View", recipe_path(recipe) %> -
						<%= link_to "Edit", edit_recipe_path(recipe) %>
				</div>
				<% end %>	

	</div>

</div>

<div class="container-fluid">
	
	<% if current_user %>
		<center>
			<%= link_to "Add Recipe", new_recipe_path, class: "btn btn-primary" %>
		</center>
	<% else %>
	<% end %>
</div>
<footer>
	<br>
	<br>
	<br>
</footer>	
	

app/views/recipes/new.html.erb
<div class="container">
	<h1>New Recipe</h1>
	<%= form_for(@recipe) do |f| %>
		<p><%= f.text_field :name, placeholder: "Name" %></p>	
		<p><%= f.text_field :instructions, placeholder: "instructions" %></p>
		<p><%= f.submit "submit" %></p>
	<% end %>	
</div>

app/views/recipes/show.html.erb
<div class="container">
	<h1>My Recipes</h1>
		<p><%= @recipe.name %></p>
		<p><%= @recipe.instructions %></p>
</div>

app/views/users/edit.html.erb
<div class="container">
	<h1>Edit User</h1>
	<%= form_for(@user) do |f| %>
		<p><%= f.text_field :first_name, placeholder: "First Name" %></p>	
		<p><%= f.text_field :last_name, placeholder: "Last Name" %></p>
		<p><%= f.email_field :email, placeholder: "Email" %></p>	
		<p><%= f.password_field :password, placeholder: "Password" %></p>
		<p><%= f.submit "Edit" %></p>
	<% end %>	
</div>

app/views/users/new.html.erb
<div class="container">
	<h1>Sign Up</h1>
	<%= form_for(@user) do |f| %>
		<p><%= f.text_field :first_name, placeholder: "First Name" %></p>	
		<p><%= f.text_field :last_name, placeholder: "Last Name" %></p>
		<p><%= f.email_field :email, placeholder: "Email" %></p>	
		<p><%= f.password_field :password, placeholder: "Password" %></p>
		<p><%= f.submit "Sign Up" %></p>
	<% end %>	
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<h1>
				Profile Page
			</h1>
			<p>
				<b>Name: </b>
				<%= current_user.first_name %>
				<%= current_user.last_name %>
			</p>
		</div>
	</div>
</div>
<br>
<br>
<div class="container"> 
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>My Recipes</h1>
	</div>
</div>
	<div class="row">
		<% current_user.recipes.each do |recipe| %>
			<div class="col-md-4 col-md-offset-2">
				<h2><%= recipe.name %></h2>
				<p>
					<em>Instructions: </em><%= recipe.instructions %>	
				</p>
				<%= link_to "Edit", edit_recipe_path(recipe) %>
			</div>
		<% end %>	
	</div>
</div>